"""Generate idempotent Snowflake governance-as-code from classifications.

Design choice: masking is driven by DIRECT column policies selected per behavior,
because a column may carry only one masking policy and we want per-field behavior
(e.g. SSN last-4 vs full mask). Tags are emitted for classification/audit. A
commented tag-based-masking alternative is included for teams who prefer inheritance.
"""
from textwrap import dedent

# behavior key -> (policy object name, data type, RETURNS body using {FULL}/{PARTIAL})
_POLICY_DEFS = {
    "full_mask_string": ("MASK_FULL_STRING", "STRING",
        "CASE WHEN IS_ROLE_IN_SESSION('{FULL}') THEN val ELSE '***MASKED***' END"),
    "mask_ssn": ("MASK_SSN", "STRING", dedent("""\
        CASE
            WHEN IS_ROLE_IN_SESSION('{FULL}')    THEN val
            WHEN IS_ROLE_IN_SESSION('{PARTIAL}') THEN 'XXX-XX-' || RIGHT(val, 4)
            ELSE '***MASKED***'
          END""")),
    "mask_email": ("MASK_EMAIL", "STRING", dedent("""\
        CASE
            WHEN IS_ROLE_IN_SESSION('{FULL}')    THEN val
            WHEN IS_ROLE_IN_SESSION('{PARTIAL}') THEN REGEXP_REPLACE(val, '^[^@]+', '****')
            ELSE '***MASKED***'
          END""")),
    "mask_phone": ("MASK_PHONE", "STRING", dedent("""\
        CASE
            WHEN IS_ROLE_IN_SESSION('{FULL}')    THEN val
            WHEN IS_ROLE_IN_SESSION('{PARTIAL}') THEN REPEAT('*', GREATEST(LENGTH(val)-4, 0)) || RIGHT(val, 4)
            ELSE '***MASKED***'
          END""")),
    "mask_card": ("MASK_CARD", "STRING", dedent("""\
        CASE
            WHEN IS_ROLE_IN_SESSION('{FULL}')    THEN val
            WHEN IS_ROLE_IN_SESSION('{PARTIAL}') THEN REPEAT('*', GREATEST(LENGTH(val)-4, 0)) || RIGHT(val, 4)
            ELSE '***MASKED***'
          END""")),
    "full_mask_number": ("MASK_FULL_NUMBER", "NUMBER",
        "CASE WHEN IS_ROLE_IN_SESSION('{FULL}') THEN val ELSE NULL END"),
    "full_mask_date": ("MASK_FULL_DATE", "DATE",
        "CASE WHEN IS_ROLE_IN_SESSION('{FULL}') THEN val ELSE NULL END"),
}

_HEADER = "-- Generated by pii-guardian. Review before running. Do NOT run as ACCOUNTADMIN.\n"


def _format_policy(gov, name, dtype, expr, full, partial):
    """Render one masking policy with tidy, consistent indentation."""
    expr = expr.format(FULL=full, PARTIAL=partial)
    indented = "\n".join(("  " + ln) if ln.strip() else ln for ln in expr.splitlines())
    return (f"CREATE MASKING POLICY IF NOT EXISTS {gov}.{name} "
            f"AS (val {dtype}) RETURNS {dtype} ->\n{indented};\n")


def _gov(roles_cfg):
    return f"{roles_cfg['governance_database']}.{roles_cfg['governance_schema']}"


def generate(classifications, roles_cfg, masking_rules):
    gov = _gov(roles_cfg)
    full = roles_cfg["roles"]["full_reader"]
    partial = roles_cfg["roles"]["partial_reader"]

    auto = [c for c in classifications if c.decision == "auto" and c.mask_behavior]
    used_behaviors = sorted({c.mask_behavior for c in auto})

    files: dict[str, str] = {}

    # 00 — classification tags (audit/discovery; no masking attached here) -----
    files["00_tags.sql"] = _HEADER + dedent(f"""\
        -- Classification tags (used for discovery, audit, and lineage).
        CREATE SCHEMA IF NOT EXISTS {gov};
        CREATE TAG IF NOT EXISTS {gov}.PII_CATEGORY
          ALLOWED_VALUES 'DIRECT_IDENTIFIER','GOV_ID','CONTACT','FINANCIAL','HEALTH','QUASI_IDENTIFIER';
        CREATE TAG IF NOT EXISTS {gov}.DATA_SENSITIVITY
          ALLOWED_VALUES 'RESTRICTED','CONFIDENTIAL','INTERNAL','PUBLIC';
        """)

    # 10 — roles -------------------------------------------------------------
    files["10_roles.sql"] = _HEADER + dedent(f"""\
        -- Privileged read roles. Grant to specific users out of band.
        -- Default analyst/reporting roles must NOT receive these, so they see masked data.
        CREATE ROLE IF NOT EXISTS {full};
        CREATE ROLE IF NOT EXISTS {partial};
        """)

    # 20 — masking policies (only the ones actually used) --------------------
    body = [_HEADER + "-- Masking policies. IF NOT EXISTS keeps re-runs safe.\n"]
    for beh in used_behaviors:
        name, dtype, expr = _POLICY_DEFS[beh]
        body.append(_format_policy(gov, name, dtype, expr, full, partial))
    files["20_masking_policies.sql"] = "\n".join(body)

    # 30 — apply classification tags ----------------------------------------
    lines = [_HEADER, "-- Tag classified columns for audit/discovery.\n"]
    for c in auto:
        lines.append(
            f"ALTER TABLE {c.database}.{c.schema}.{c.table} MODIFY COLUMN {c.column}\n"
            f"  SET TAG {gov}.PII_CATEGORY = '{c.category}', {gov}.DATA_SENSITIVITY = '{c.sensitivity}';")
    files["30_classification_tags.sql"] = "\n".join(lines) + "\n"

    # 40 — apply direct masking policies ------------------------------------
    lines = [_HEADER, "-- Apply masking. A column may hold only ONE masking policy.\n"]
    for c in auto:
        pname = _POLICY_DEFS[c.mask_behavior][0]
        lines.append(
            f"ALTER TABLE {c.database}.{c.schema}.{c.table} MODIFY COLUMN {c.column} "
            f"SET MASKING POLICY {gov}.{pname};  -- {c.category}/{c.sensitivity} conf={c.confidence}")
    files["40_apply_masking.sql"] = "\n".join(lines) + "\n"

    # 50 — optional tag-based masking ---------------------------------------
    files["50_tag_based_masking_optional.sql"] = _HEADER + dedent(f"""\
        -- OPTIONAL alternative: tag-based masking (uniform full-mask, auto-applies to
        -- ANY column carrying PII_CATEGORY). A column can hold only one masking policy,
        -- so do NOT combine this with 40_apply_masking.sql on the same columns.
        -- ALTER TAG {gov}.PII_CATEGORY SET MASKING POLICY {gov}.MASK_FULL_STRING;  -- STRING cols
        -- ALTER TAG {gov}.PII_CATEGORY SET MASKING POLICY {gov}.MASK_FULL_NUMBER;  -- NUMBER cols
        -- ALTER TAG {gov}.PII_CATEGORY SET MASKING POLICY {gov}.MASK_FULL_DATE;    -- DATE cols
        """)

    # 60 — optional column encryption ---------------------------------------
    enc = masking_rules.get("encrypt_columns") or []
    lines = [_HEADER, dedent("""\
        -- OPTIONAL top-tier column encryption. Use ONLY where masking is insufficient.
        -- Source keys from a Snowflake SECRET or external KMS; never hardcode. Note that
        -- encryption breaks equality joins/search unless deterministic, and you own rotation.
        """)]
    if not enc:
        lines.append("-- (no columns configured in masking_rules.yaml: encrypt_columns)\n")
    else:
        for fq in enc:
            db, sch, tbl, col = fq.split(".")
            lines.append(dedent(f"""\
                -- Encrypt {fq}
                -- ALTER TABLE {db}.{sch}.{tbl} ADD COLUMN {col}_ENC BINARY;
                -- UPDATE {db}.{sch}.{tbl}
                --   SET {col}_ENC = ENCRYPT_RAW(TO_BINARY({col}, 'UTF-8'),
                --        (SELECT key FROM {gov}.KEYS), TO_BINARY('{tbl}', 'UTF-8'));
                -- ALTER TABLE {db}.{sch}.{tbl} DROP COLUMN {col};  -- after verifying decrypt path
                """))
    files["60_encryption_optional.sql"] = "\n".join(lines)

    # 99 — validation --------------------------------------------------------
    samples = [c for c in auto if c.type_group == "STRING"][:2]
    lines = [_HEADER, "-- Prove masking behaves per role. Replace LIMIT/preds as needed.\n"]
    for c in samples:
        sel = f"SELECT {c.column} FROM {c.database}.{c.schema}.{c.table} LIMIT 5;"
        lines.append(dedent(f"""\
            -- {c.fqcn}  (policy: {_POLICY_DEFS[c.mask_behavior][0]})
            USE ROLE ANALYST;            {sel}   -- expect masked
            USE ROLE {partial};   {sel}   -- expect partial (if supported)
            USE ROLE {full};      {sel}   -- expect cleartext
            """))
    if not samples:
        lines.append("-- (no string columns auto-classified in this run)\n")
    files["99_validation.sql"] = "\n".join(lines)

    return files, auto
